version: 2
updates:
  - package-ecosystem: gradle
    directory: "/"
    schedule:
      interval: daily
    ignore:
      - dependency-name: "io.papermc.paper:paper-api"
        update-types: [ "version-update:semver-patch" ]
      - dependency-name: "me.outspending.biomesapi:BiomesAPI"
        update-types: [ "version-update:semver-patch" ]
